language: cpp
dist: xenial
compiler: gcc
addons:
  apt:
    packages:
      - libgoogle-glog-dev
      - libboost-system-dev
      - libdouble-conversion-dev
      - libjemalloc-dev
      - libboost-all-dev
      - libssl-dev

before_script:
  - git clone https://github.com/facebook/folly.git
  # will change PATH so we find cmake,...
  - source ./build/travis_${TRAVIS_OS_NAME}.sh

script:
  - cmake wdt -DBUILD_TESTING=on
  - make -j 4
  - CTEST_OUTPUT_ON_FAILURE=1 make test
